-- MySQL Script generated by MySQL Workbench
-- 09/12/24 22:02:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema desarrollo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `desarrollo` ;

-- -----------------------------------------------------
-- Schema desarrollo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desarrollo` DEFAULT CHARACTER SET utf8 ;
USE `desarrollo` ;

-- -----------------------------------------------------
-- Table `desarrollo`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desarrollo`.`alumno` (
  `idalumno` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalumno`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desarrollo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desarrollo`.`usuario` (
  `correo` VARCHAR(45) NOT NULL,
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(45) NOT NULL,
  `idAlumno` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `idallumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `desarrollo`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idallumno_idx` ON `desarrollo`.`usuario` (`idAlumno` ASC);


-- -----------------------------------------------------
-- Table `desarrollo`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desarrollo`.`Profesor` (
  `idProfesor` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `RFC` VARCHAR(14) NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desarrollo`.`UnidadAprendizaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desarrollo`.`UnidadAprendizaje` (
  `idUnidadAprendizaje` INT NOT NULL,
  `nombreUnidadAprendizaje` VARCHAR(50) NULL,
  `horasClase` INT NULL,
  `horasTaller` INT NULL,
  `horasLaboratorio` INT NULL,
  PRIMARY KEY (`idUnidadAprendizaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desarrollo`.`Asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desarrollo`.`Asignacion` (
  `idAsignacion` INT NOT NULL,
  `idProfesor` INT NULL,
  `idUnidadAprendizaje` INT NULL,
  PRIMARY KEY (`idAsignacion`),
  CONSTRAINT `FK_1_idProfesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `desarrollo`.`Profesor` (`idProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_2_UnidadAprendizaje`
    FOREIGN KEY (`idUnidadAprendizaje`)
    REFERENCES `desarrollo`.`UnidadAprendizaje` (`idUnidadAprendizaje`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `FK_1_idProfesor_idx` ON `desarrollo`.`Asignacion` (`idProfesor` ASC);

CREATE INDEX `FK_2_UnidadAprendizaje_idx` ON `desarrollo`.`Asignacion` (`idUnidadAprendizaje` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
